version: "2"

services:
    bot:
        build: .
        command: python -u main.py
        volumes:
            - ./bot:/bot
            - ./leagues:/leagues
            - ./players:/players
        environment:
            - MODE=dev
        restart: always